### ISSUE TITLE
Table headings are squashing into each other

### ISSUE THREAD

**Issue by TahaKaawan** [Aathish04/rep-manim#3]
I have this issue where adding a 2nd table column results in column heading squashes with the 1st table column heading. I discussed the issue with Aathish04 and he said there is a bug in the alignment code

**Comment by Aathish04** [comment]
Sorry for taking so long; it was a busy year.

In any case, you should now use the `Table` mobject in ManimCommunity.
You can find documentation for it here: https://docs.manim.community/en/stable/reference/manim.mobject.table.html
